version: '3'

services:
  database:
    container_name: procatty_database
    image: postgres:13-alpine
    restart: always

    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_ROOT: $POSTGRES_ROOT
      POSTGRES_DATABASE: $POSTGRES_DATABASE

    env_file: .env

    ports:
      - $DB_LOCAL_PORT:$POSTGRES_PORT

  app:
    image: node:lts-alpine
    restart: always

    volumes:
      - ./:/app

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - port=$APP_LOCAL_PORT

    ports:
      - ${APP_LOCAL_PORT}:${APP_DOCKER_PORT}

    depends_on:
      - database

networks:
  default:
    driver: bridge
